import { Show, Contact } from "@/types";

export const mockShows: Show[] = [
  {
    id: "1",
    title: "햄릿",
    subtitle: "Hamlet",
    description:
      "덴마크 왕자 햄릿이 아버지의 죽음에 얽힌 진실을 파헤치며 복수를 결심하는 이야기. 사랑, 배신, 죽음이 교차하는 셰익스피어의 대표작을 젊은 시각으로 재해석합니다. 무대 위에서 펼쳐지는 인간의 가장 깊은 내면을 경험하세요.",
    poster_url: "https://placehold.co/400x530/6D3115/F4EDE3?text=Hamlet",
    venue: "대학로 소극장",
    venue_address: "서울특별시 종로구 대학로 123",
    schedule_start: "2026.05.10",
    schedule_end: "2026.05.25",
    cast_members: ["김민준 (햄릿)", "이수진 (오필리아)", "박지훈 (클로디어스)", "최현우 (폴로니어스)"],
    directions: "4호선 혜화역 1번 출구에서 도보 5분",
    ticket_url: "https://example.com/ticket/hamlet",
    status: "approved",
    created_at: "2026-04-20",
    organizer_id:"p1",
    performer_name: "극단 청춘",
  },
  {
    id: "2",
    title: "벚꽃 동산",
    subtitle: "The Cherry Orchard",
    description:
      "체호프의 희곡을 현대적으로 재해석한 작품. 변화하는 세상 속에서 과거에 집착하는 가족의 이야기를 통해 우리 시대의 이야기를 들여다봅니다. 잃어버린 것들에 대한 아름다운 애도.",
    poster_url: "https://placehold.co/400x530/3D6FC8/F4EDE3?text=Cherry+Orchard",
    venue: "홍익대학교 아트센터",
    venue_address: "서울특별시 마포구 와우산로 94",
    schedule_start: "2026.06.01",
    schedule_end: "2026.06.15",
    cast_members: ["정예린 (라네프스카야)", "최현우 (트로피모프)", "한지우 (안야)"],
    directions: "2호선 홍대입구역 9번 출구에서 도보 10분",
    ticket_url: "https://example.com/ticket/cherry",
    status: "approved",
    created_at: "2026-04-22",
    organizer_id:"p2",
    performer_name: "극단 봄날",
  },
  {
    id: "3",
    title: "고도를 기다리며",
    subtitle: "Waiting for Godot",
    description:
      "베케트의 부조리극. 두 남자가 오지 않는 고도를 기다리며 나누는 이야기. 삶의 무의미함과 그 속에서 찾는 의미에 대한 철학적 탐구. 깊은 여운을 남기는 작품입니다.",
    poster_url: "https://placehold.co/400x530/1B2842/F4EDE3?text=Godot",
    venue: "명동예술극장",
    venue_address: "서울특별시 중구 명동길 35",
    schedule_start: "2026.05.20",
    schedule_end: "2026.06.05",
    cast_members: ["이태양 (블라디미르)", "송지현 (에스트라공)"],
    directions: "4호선 명동역 8번 출구에서 도보 3분",
    status: "approved",
    created_at: "2026-04-21",
    organizer_id:"p3",
    performer_name: "극단 기다림",
  },
  {
    id: "4",
    title: "오이디푸스",
    subtitle: "Oedipus Rex",
    description:
      "소포클레스의 고전 비극. 운명에 맞서 싸우는 인간의 이야기를 현대적 무대로 구현합니다. 진실을 향한 집착이 불러오는 비극적 결말. 고대 그리스의 지혜가 오늘을 말합니다.",
    poster_url: "https://placehold.co/400x530/3A5E42/F4EDE3?text=Oedipus",
    venue: "세종문화회관 M씨어터",
    venue_address: "서울특별시 종로구 세종대로 175",
    schedule_start: "2026.07.01",
    schedule_end: "2026.07.20",
    cast_members: ["박준혁 (오이디푸스)", "김하영 (이오카스테)", "이준호 (크레온)"],
    directions: "5호선 광화문역 1번 출구에서 도보 5분",
    ticket_url: "https://example.com/ticket/oedipus",
    status: "approved",
    created_at: "2026-04-23",
    organizer_id:"p4",
    performer_name: "청년극단 테스피스",
  },
];

export const mockContacts: Contact[] = [
  {
    id: "c1",
    name: "홍길동",
    email: "hong@example.com",
    message: "공연자 신청 관련 문의드립니다.",
    status: "pending",
    created_at: "2026-04-22",
  },
];
